### ISSUE TITLE
index.rst: flux-tree link broken after flux-sched#956

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-docs#151]
I think a link is no longer working on the [FAQ page](https://flux-framework.readthedocs.io/en/latest/faqs.html) after landing flux-framework/flux-sched#956, which moved  `flux-tree` to the test suite and changed paths in the repo.

The link just needs to be updated to reflect the new path to the test suite.

**Comment by grondo** [comment]
Nice catch!

**Comment by grondo** [comment]
I also noticed a `flux tree` mention [here](https://flux-framework.readthedocs.io/en/latest/faqs.html#how-do-i-efficiently-launch-a-large-number-of-jobs-to-flux). We should search the docs repo for mention of this test utility.

Actually that FAQ entry is out of date since we have `flux mini submit --cc` and `flux mini bulksubmit` commands. I'll open a separate issue to update the entry.

**Comment by cmoussa1** [comment]
Good point. The issue I opened above was a result of a failure when running `make linkcheck`, and that was the only one that was caught (I think). 

Maybe I should go ahead and scan the docs site and check the links. It would probably be good to get those sorted out in case anybody takes a look at those while/after attending @milroy's presentation and tutorial.

**Comment by grondo** [comment]
Thanks! (I noticed the FAQ entry I referenced above is the same one you fixed, so I did not open an issue specifically)
