### ISSUE TITLE
Some RTD section titles could be improved

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-docs#67]
Just noticed while navigating the [rtd site](https://flux-framework.readthedocs.io/en/latest/) that a couple section titles could use improvment:

 * The RFC Index is titled "[API Reference](https://flux-framework.readthedocs.io/en/latest/#api-reference)"
 * The link to flux-core mapages is titled [Welcome to flux-core's documentation!](https://flux-framework.readthedocs.io/en/latest/#command-reference)

**Comment by SteVwonder** [comment]
> The RFC Index is titled "API Reference"

Changing this is easy.  It's just a one line change in this repo. Does changing the name to "All RFCs" and moving it directly underneath "Contributor Relevant RFCs" work?

> The link to flux-core mapages is titled Welcome to flux-core's documentation!

So this requires changing the title (or subsection title) of the index.rsts files in the flux-core repo.  I propose that rather than using or changing the main title for the flux-core subproject "Welcome to flux-core's documentation", we change the subsection "Man Pages" to "Flux-core Man Pages" and then use that title (via an explicit label and reference).  Then in the future, we can link to "Flux-sched Man Pages", "Flux-accounting Man Pages", etc.  If we do that, then maybe "Command Reference" should be changed to "Man Pages"?
